import { DisplayHtmlRaw } from "../../display-data/html/html-raw.js"
import { HtmlFormat } from "../../content.reader/html/format/html-format.js";
import { IFieldFile } from "../../lib/i-field-file.js"
import { HtmlCodeProvider } from "./provider/html-code-provider.js";
 
export class ExportForHtmlRaw{
    EData: IFieldFile;


    constructor(EData: IFieldFile){
        this.EData = EData;
    }
    ExportForHtml() {

        var preview = 
        ["<!-- Auto Generated By D-GEN.SAVEDATA.IR -->" , new HtmlCodeProvider(this.EData).GetHtmlData(null) , "<!-- End Auto -->"].join("\n")
        
 
        var rawtext = preview.split("\n").map(p => p.trimStart()).join("\n");
        rawtext = new HtmlFormat().format(rawtext);
     
        return rawtext;
    }
}
